
name: Lighthouse report 
on: [deployment_status]
jobs:
  lighthouse-report-dev:
    runs-on: ubuntu-20.04
    if: |
      github.event.deployment_status.state == 'success' && 
      contains(github.event.deployment.environment, 'kube')
    steps:
      - name: checkout code 
        uses: actions/checkout@v2 
        with:
          ref: ${{ github.event.deployment.ref }}
      - name: setup nodejs
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 14.18
      - name: install lhci 
        run: npm i -g @lhci/cli@0.5.x
      - name: run develop report
        if: contains(github.event.deployment.payload, 'develop')
        env:
          LHCI_BUILD_CONTEXT__CURRENT_BRANCH: develop
        run: lhci autorun --config lighthouse/${{ github.event.deployment.environment}}.yml 
      - name: run report
        env:
          LHCI_BUILD_CONTEXT__CURRENT_BRANCH: ${{ github.event.deployment.ref }}
        run: lhci autorun --config lighthouse/${{ github.event.deployment.environment}}.yml
      - name: Verify Lighthouse Check results
        uses: actions/checkout@v2
        with:
          lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
          minAccessibilityScore: "80"
          minBestPracticesScore: "90"
          minPerformanceScore: "70"
          minProgressiveWebAppScore: "0"
          minSeoScore: "80"
  lighthouse-report-staging:
    runs-on: ubuntu-20.04
    if: |
      github.event.deployment_status.state == 'success' && 
      github.event.deployment.environment == 'staging'
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.deployment.ref }}
      - name: setup nodejs
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 14.18
      - name: install lhci
        run: npm i -g @lhci/cli@0.5.x
      - name: run report
        env:
          LHCI_BUILD_CONTEXT__CURRENT_BRANCH: ${{ github.event.deployment.ref }}
        run: lhci autorun --config lighthouse/staging.yml 
